version: '3.8'

services:
  db:
    image: postgres:14-alpine
    container_name: prepmate_db
    environment:
      POSTGRES_USER: prepmate_user
      POSTGRES_PASSWORD: prepmate_password
      POSTGRES_DB: prepmate
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  backend:
    build: 
      context: ./backend
      dockerfile: DockerFile
    container_name: prepmate_backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - DB_URL=jdbc:postgresql://db:5432/prepmate
      - DB_USERNAME=prepmate_user
      - DB_PASSWORD=prepmate_password
      - FRONTEND_URL=http://localhost:3000
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - GEMINI_API_URL=https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent
      - GROQ_API_KEY=${GROQ_API_KEY}
      - PINECONE_API_KEY=${PINECONE_API_KEY}
      - PINECONE_INDEX_HOST=${PINECONE_INDEX_HOST}
      - JWT_SECRET=${JWT_SECRET:-PrepIntAISecretKeyWillBeUsedIfNoneIsProvidedInPropertiesSecret12345!}
    depends_on:
      - db
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: prepmate_frontend
    ports:
      - "3000:80"
    environment:
      - VITE_API_BASE_URL=http://localhost:8080
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  pgdata:
