spring.application.name=prepmate
spring.profiles.active=${SPRING_PROFILES_ACTIVE:local}
frontend.url=${FRONTEND_URL:http://localhost:5173}

# API Keys mapped to Environment Variables
gemini.api.url=${GEMINI_API_URL:}
gemini.api.key=${GEMINI_API_KEY:}
groq.api.key=${GROQ_API_KEY:}
pinecone.api.key=${PINECONE_API_KEY:}
pinecone.index.host=${PINECONE_INDEX_HOST:}

# Database Configuration
spring.datasource.url=${DATABASE_URL:}
spring.datasource.username=${DATABASE_USERNAME:}
spring.datasource.password=${DATABASE_PASSWORD:}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.datasource.hikari.maximum-pool-size=5
spring.jpa.open-in-view=false
spring.web.error.include-message=always

# JWT Security
jwt.secret=${JWT_SECRET:}