# Postgres Configurations
spring.application.name=prepintai
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.datasource.hikari.maximum-pool-size=5
spring.jpa.open-in-view=false
spring.web.error.include-message=always

# Gemini API Configurations
gemini.api.url=${GEMINI_API_URL}
gemini.api.key=${GEMINI_API_KEY}